version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_URL=/password-checker
    container_name: password-checker-backend
    ports:
      - "32777:5001"
    environment:
      - FLASK_ENV=production
    networks:
      - password-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - PUBLIC_URL=/password-checker      
    container_name: password-checker-frontend
    ports:
      - "32778:3001"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5001
    networks:
      - password-network

networks:
  password-network:
    driver: bridge
